# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/JS-DevTools/eslint-config-modular

extends:
  - modular/node

env:
  jquery: true

globals:
  SwaggerParser: false

  # Google Analytics
  gtag: false

  # ACE Editor
  ace: false
